# Generated by Django 4.2.3 on 2024-02-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/student'),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(choices=[('CYBER SECURITY', 'CYBER SECURITY'), ('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('SOFTWARE ENGINEERING', 'SOFTWARE ENGINEERING'), ('MICROBIOLOGY', 'MICROBIOLOGY'), ('INDUSTRIAL CHEMISTRY', 'INDUSTRIAL CHEMISTRY'), ('BIOCHEMISTRY', 'BIOCHEMISTRY'), ('BUSINESS ADMINISTRATION', 'BUSINESS ADMINISTRATION'), ('ECONOMICS', 'ECONOMICS'), ('ACCOUNTING', 'ACCOUNTING'), ('MASS COMMUNICATION', 'MASS COMMUNICATION'), ('CRIMINOLOGY', 'CRIMINOLOGY')], default='COMPUTER SCIENCE', max_length=100),
        ),
    ]
